services:
  - type: web
    name: menu-compras
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: menu-compras-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: menu-compras-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: menu-compras-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: menu-compras-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: menu-compras-db
          property: database
